// <auto-generated />
using System;
using AutoTrade.Trading.Handlers.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTrade.Trading.Handlers.Model.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20260919111927_ProposalLegStopDistance")]
    partial class ProposalLegStopDistance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.ActiveBasketVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivatedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveBasketVersion");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BasketDraftLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RiskCap")
                        .HasColumnType("REAL");

                    b.Property<double>("StopDistancePips")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketDraftLeg");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BasketDraftPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyLossLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RiskPerBasket")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketDraftPolicy");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BasketVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BasketId", "Number")
                        .IsUnique();

                    b.ToTable("BasketVersion");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BasketVersionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RiskCap")
                        .HasColumnType("REAL");

                    b.Property<double>("StopDistancePips")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeFrame")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("VersionId", "Symbol")
                        .IsUnique();

                    b.ToTable("BasketVersionLeg");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BasketVersionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DailyLossLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RiskPerBasket")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VersionId")
                        .IsUnique();

                    b.ToTable("BasketVersionPolicy");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BrokerAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessTokenCipher")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccessTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CtidTraderAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenCipher")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Environment")
                        .IsUnique();

                    b.ToTable("BrokerAuthorization");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BrokerAuthorizationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("BrokerAuthorizationAttempt");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.BrokerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerEventId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LegId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerEventId")
                        .IsUnique();

                    b.HasIndex("ExecutionId");

                    b.ToTable("BrokerEvent");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompensationOfExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("Execution");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.ExecutionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AveragePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("BrokerOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledVolumeUnits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEventAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumeUnits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("ExecutionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ExecutionLeg");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.GateEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ObservedValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId", "Ordinal")
                        .IsUnique();

                    b.ToTable("GateEvaluation");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.JournalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.ToTable("JournalEvent");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.KillSwitchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEngaged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KillSwitchState");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.MarketManagerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnalysisRunning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCycleAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarketManagerState");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.MarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AccountBalance")
                        .HasColumnType("REAL");

                    b.Property<double>("AccountEquity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("RealizedPnlToday")
                        .HasColumnType("REAL");

                    b.Property<double>("UnrealizedPnl")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MarketSnapshot");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.MarketSnapshotLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SpreadPips")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("VolatilityPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Ordinal")
                        .IsUnique();

                    b.ToTable("MarketSnapshotLeg");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.OperatorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("OperatorSession");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BasketVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecidedByOperatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<double>("ExpectedRiskPercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProposedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("Status", "ProposedAtUtc");

                    b.ToTable("Proposal");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.ProposalLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RiskCap")
                        .HasColumnType("REAL");

                    b.Property<double>("StopDistancePips")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId", "Ordinal")
                        .IsUnique();

                    b.ToTable("ProposalLeg");
                });

            modelBuilder.Entity("AutoTrade.Trading.Handlers.Model.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BrokerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTradingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBrokerSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReconciledUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TradingAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
